### ISSUE TITLE
Unable to run tests for "linked" component

### ISSUE THREAD

**Issue by allanpope** [hooroo/roo-ui#110]
I'm running into an issue where tests are not running after linking `roo-ui` to an app.

It breaks due to export being ES6.

<img width="1265" alt="screen shot 2018-07-10 at 11 24 06 am" src="https://user-images.githubusercontent.com/2561365/42483909-ccde6d36-8433-11e8-945a-b01bbc8491bf.png">

Changing `.dev/index.js` to `module.exports = require('styled-components')` fixes that issue but then causes:

<img width="931" alt="screen shot 2018-07-10 at 11 25 29 am" src="https://user-images.githubusercontent.com/2561365/42483973-fd802e2a-8433-11e8-96a6-231686218d5d.png">

More info on the above error here https://github.com/styled-components/jest-styled-components/issues/112

**Comment by jonathanly** [comment]
Migrate to clubhouse
