### ISSUE TITLE
A new green

### ISSUE THREAD

**Issue by dougmcclurg** [hooroo/roo-ui#144]

**Comment by camille-hooroo** [comment]
https://qantashotels.slack.com/archives/C9H7H0GTD/p1534382931000100

*Proposed changes to green*
I pulled out some elements/components that has green from the sketch files and took the shades of green we’ve been using
- narrow down greens from 4 shades to 3 
- #dcf5dc #39b683 #00af6a #56a231 ------> #dcf5dc (bg) #1D8849 (icons) #005925 (text)
____ the icon colour #1D8849 on a white background gets an AA score. the text colour #005925 on a white background gets AAA 
- change comparison: https://app.zeplin.io/project/5b74d23f2196c9b23de032c3/screen/5b74d269f63f4f070998080f
- samples from different pages across different projects: https://zpl.io/25rgOkn 

*AAA guidelines*
- we can’t use the red colour on the light green background for links anymore. we can only use #323232 to pass AAA
- One design sample from Extranet was using a green text colour #39B683 for the “Request Submitted”  header, but the new green text colour #005925 is way too close to #323232 or #222222 so I’m proposing that in these cases we keep the header text dark gray, then just use green for the icon. there isn’t a notable enough difference between the new text green to the content text colour to make the header colour different. (it’s the last example in https://zpl.io/2yyBOjK)
