### ISSUE TITLE
Icon does not support responsive sizes

### ISSUE THREAD

**Issue by ehyland** [hooroo/roo-ui#163]
It would be great if size props on icon was responsive.

**Comment by jonathanly** [comment]
Migrate to clubhouse

**Comment by talbet** [comment]
This should be easier once we upgrade to StyledSystem v5 and have access to the `css` prop

**Comment by talbet-qga** [comment]
Perhaps we should try and fix this sooner rather than later since StyledSystem v5 upgrade is blocked for the foreseeable future due to https://github.com/styled-system/styled-system/issues/1058

**Comment by ehyland** [comment]
Fixed awhile back https://github.com/hooroo/roo-ui/pull/311
