### ISSUE TITLE
Tests failing in local development and passing in CI

### ISSUE THREAD

**Issue by talbet** [hooroo/roo-ui#176]
I have tests breaking in the following files

* `packages/components/src/Dropdown/Dropdown.test.js`
* `packages/components/src/Autocomplete/Autocomplete.test.js`

But they are passing in the CI without any modification.

They are snapshot tests and A11y tests coming from `react-axe`. It looks like it is due to a version mismatch in the `react-axe` dependency, but `yarn.lock` should prevent this?

**Comment by jonathanly** [comment]
Migrate to clubhouse
