### ISSUE TITLE
flex shorthand can easily break on IE11

### ISSUE THREAD

**Issue by talbet** [hooroo/roo-ui#187]
the `Box` component uses the built-in styled system `flex` function. Unfortunately the flex shorthand works differently in IE11 and modern browsers.

It is very easy to forget to use `Flex="1 1 auto"` and use `Flex="1"` instead which causes IE11 bugs.

Using flex-grow would be less confusing, but there is no built in `flexGrow` function. It might be worth building one and adding it to Box.

**Comment by talbet** [comment]
Or, maybe we can look at solving this at an autoprefixer level

Or, maybe we can add an alias to the `qantas.js` theme. ("1" = "1 1 auto")

**Comment by jonathanly** [comment]
Migrated to clubhouse
