### ISSUE TITLE
Misnaming: `inline` prop on `Link` sets style to `underline`...

### ISSUE THREAD

**Issue by christian314159** [hooroo/roo-ui#193]
On the **Link** component is this bit of logic:
```
${props => props.inline && css`
    &, &:hover {
      text-decoration: underline;
      color: inherit;
    }
  `}
```
This is a bit confusing as `inline` is usually associated with the `display` property, but what it really does is set the styled to `underline`.

 My suggestion would be to:
- make both work (`inline` and `underline` to both set text to be underlined)
- give out a deprecation warning for `inline`; ask people to update their code to `inline`
- remove `inline` option after x weeks

**Comment by jonathanly** [comment]
Migrated to clubhouse
