### ISSUE TITLE
Decouple Heading style and markup

### ISSUE THREAD

**Issue by olyism** [hooroo/roo-ui#319]
Currently, heading font-sizes are controlled by the markup, i.e. `Heading.h1`, `Heading.h2` and so forth.

This causes problems when the visual design requires a font size that is different to the heading. For accessibility, we need to use the correct heading order, which means we need to apply a lot of styles overrides to achieve the look.

Take this destination page for example:

![image](https://user-images.githubusercontent.com/7202667/83143144-d6108680-a134-11ea-92ac-086a0b93376d.png)

The property title is the same font size as `Heading.h1`, but the markup needs to be `h4` in the heading order.

**Comment by ehyland** [comment]
@olyism give this a crack 

```js
<Heading.h1 as="h4">
  Styled like h1, renders h4
</Heading.h1>
```

**Comment by ehyland** [comment]
@olyism I'm closing this one for now. Feel free to reopen if you don't think the `as` prop is a suitable solution
