### ISSUE TITLE
Buttons which look like Links

### ISSUE THREAD

**Issue by allanpope** [hooroo/roo-ui#57]
What should we do with them?

<img width="145" alt="screen shot 2018-05-29 at 2 14 22 pm" src="https://user-images.githubusercontent.com/2561365/40637794-a584fe6c-634a-11e8-8a0b-19e24dab668e.png">

**Comment by dougmcclurg** [comment]
Do buttons need sizes. small, med, large, max-stadium?

**Comment by angusfretwell** [comment]
test

**Comment by allanpope** [comment]
Close in favour of #63
