### ISSUE TITLE
Add loading state to <Button />

### ISSUE THREAD

**Issue by allanpope** [hooroo/roo-ui#65]
Add spinner to Button to indicate loading state

**Comment by angusfretwell** [comment]
Been giving this some thought, it seems most sites just apply the pattern of disabling the button (and sometimes changing the text) to indicate a loading state (usually a form submission). IMO adding a spinner or some other animated thing might be a bit visually distracting, though I do think it's important to communicate the loading state clearly.

**Comment by jonathanly** [comment]
Migrated to clubhouse
